name: e2e Playwright GAD tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    environment: test-env-gad
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm i

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Clone GAD repo
        run: git clone https://github.com/jaktestowac/gad-gui-api-demo.git
        
      - name: Run Playwright tests
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          USER_INCORRECT_EMAIL: ${{ secrets.USER_INCORRECT_EMAIL }}
          USER_INCORRECT_PASSWORD: ${{ secrets.USER_INCORRECT_PASSWORD }}
        run: npm run test