name: e2e Playwright GAD tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    environment: test-env-gad
    permissions:
      contents: read
      checks: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"
          cache-dependency-path: '**/package-lock.json'

      - name: Cache node_modules
        uses: actions/cache@v4
        id: node-cache
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Cache Playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium

      - name: Clone GAD repo
        run: git clone https://github.com/jaktestowac/gad-gui-api-demo.git

      - name: Install GAD dependencies
        run: |
          cd gad-gui-api-demo
          npm install

      - name: Start GAD application
        run: |
          cd gad-gui-api-demo
          npm run start &
          sleep 10

      - name: Check GAD status
        run: |
          curl http://localhost:3000/api/about
          curl http://localhost:3000/api/health

      - name: Run Playwright tests
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          USER_INCORRECT_EMAIL: ${{ secrets.USER_INCORRECT_EMAIL }}
          USER_INCORRECT_PASSWORD: ${{ secrets.USER_INCORRECT_PASSWORD }}
        run: npm run test -- --reporter=html

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  publish:
    name: Publish Report
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: report-data

      - name: Organize report structure
        run: |
          mkdir -p playwright-report
          mv report-data/* playwright-report/

      - name: Setup Pages
        if: hashFiles('playwright-report/index.html') != ''
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        if: hashFiles('playwright-report/index.html') != ''
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report/

      - name: Deploy to GitHub Pages
        if: hashFiles('playwright-report/index.html') != ''
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Display deployment URL
        if: steps.deployment.outcome == 'success'
        run: |
          echo "📊 Test Report deployed to: ${{ steps.deployment.outputs.page_url }}"